# Generated by Django 5.2 on 2025-05-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="total",
        ),
        migrations.AddField(
            model_name="direccionenvio",
            name="ciudad",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orden",
            name="fecha_confirmacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="direccionenvio",
            name="direccion",
            field=models.CharField(max_length=200),
        ),
    ]
